---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Get Changed Images"

on:
  workflow_call:
    outputs:
      addedOrModified:
        description: "Whether any files were added or modified"
        value: ${{ jobs.get-changed-images.outputs.addedOrModified }}
      addedOrModifiedImages:
        description: "The images that were added or modified"
        value: ${{ jobs.get-changed-images.outputs.addedOrModifiedImages }}

jobs:
  get-changed-images:
    name: Get Changed Images
    runs-on: ubuntu-latest
    outputs:
      addedOrModified: "${{ steps.changed-files.outputs.changed_files != '[]' }}"
      addedOrModifiedImages: "${{ steps.changed-containers.outputs.addedOrModifiedImages }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: apps/**
          include_only_directories: true
          max_depth: 2

      - if: ${{ needs.changed-files.outputs.changed_files != '[]' }}
        name: Determine changed images
        id: changed-containers
        shell: bash
        run: |
          IMAGES=$( \
              echo '${{ steps.changed-files.outputs.changed_files }}' \
                  | jq --raw-output 'map(sub("^apps/"; "")) | join(",")' \
          )
          echo "addedOrModifiedImages=${IMAGES}" >> $GITHUB_OUTPUT
